= SUSE Documentation Styleguide

This guide provides answers to writing, style, and layout questions commonly
arising when editing SUSE documentation. The markup reference at the end of
the guide will help you choose the right XML element for your
purpose. Following this guide will make your documentation more understandable
and easier to translate.

The Style Guide is published at
https://doc.opensuse.org/documentation/styleguide/[doc.opensuse.org, HTML without change log].

You can also find pre-built PDF versions in this repository:

* https://github.com/SUSE/doc-styleguide/raw/master/prebuilt/current/styleguide_with_changelog.pdf[PDF with change log]
* https://github.com/SUSE/doc-styleguide/raw/master/prebuilt/current/styleguide_plain.pdf[PDF without change log]

Contributing
-------------

If you would like to contribute, please fork this repository and send
pull requests. Always use the `develop` branch for your edits! +
Contributors with direct access to the repository are encouraged to use the
git-flow-avh workflow (package `git-flow-avh`). However, this is not a must.

.*No commits to master*
NOTE: Please do not make any commits to the `master` branch. `master` is
reserved for releases only. Always commit to `develop`.
